# Generated by Django 4.0.3 on 2022-03-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='value',
            field=models.IntegerField(null=True),
        ),
    ]
