# Generated by Django 4.0.3 on 2022-03-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0002_credit_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='Credit',
            field=models.IntegerField(null=True),
        ),
    ]
