# Generated by Django 4.0.3 on 2022-03-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0003_credit_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
