# Generated by Django 4.0.3 on 2022-03-11 20:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0005_rename_auther_credit_account_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='Credit',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='Destination_account',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='created',
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit.credit')),
            ],
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit.credit')),
            ],
        ),
    ]
